main:
	gcc -o main main.c engine.c -I./lua/include -L./lua/lib -l:liblua.a -lm -ggdb
	# TODO: handle windows bin
	# x86_64-w64-mingw32-gcc -o main_windows.exe main.c engine.c -I.\lua\include -L.\lua\lib -l:liblua.a -lm -ggdb
	#gcc -o main main.c -I./lua/include -L./lua/lib -l:liblua.a -lm -ggdb
