#ifndef RMP_KEYBOARD_H_
#define RMP_KEYBOARD_H_

#include <stdbool.h>

// Keyboard API functions

// Key enumeration (complete version)
typedef enum {
    // Control keys
    RMP_KEY_CTRL_A, RMP_KEY_CTRL_B, RMP_KEY_CTRL_C, RMP_KEY_CTRL_D, RMP_KEY_CTRL_E,
    RMP_KEY_CTRL_F, RMP_KEY_CTRL_G, RMP_KEY_CTRL_H,
    RMP_KEY_CTRL_K, RMP_KEY_CTRL_L, RMP_KEY_CTRL_M, RMP_KEY_CTRL_N, RMP_KEY_CTRL_O,
    RMP_KEY_CTRL_P, RMP_KEY_CTRL_Q, RMP_KEY_CTRL_R, RMP_KEY_CTRL_S, RMP_KEY_CTRL_T,
    RMP_KEY_CTRL_U, RMP_KEY_CTRL_V, RMP_KEY_CTRL_W, RMP_KEY_CTRL_X, RMP_KEY_CTRL_Y,
    RMP_KEY_CTRL_Z,

    // Alt keys
    RMP_KEY_ALT_A, RMP_KEY_ALT_B, RMP_KEY_ALT_C, RMP_KEY_ALT_D, RMP_KEY_ALT_E,
    RMP_KEY_ALT_F, RMP_KEY_ALT_G, RMP_KEY_ALT_H, RMP_KEY_ALT_I, RMP_KEY_ALT_J,
    RMP_KEY_ALT_K, RMP_KEY_ALT_L, RMP_KEY_ALT_M, RMP_KEY_ALT_N, RMP_KEY_ALT_O,
    RMP_KEY_ALT_P, RMP_KEY_ALT_Q, RMP_KEY_ALT_R, RMP_KEY_ALT_S, RMP_KEY_ALT_T,
    RMP_KEY_ALT_U, RMP_KEY_ALT_V, RMP_KEY_ALT_W, RMP_KEY_ALT_X, RMP_KEY_ALT_Y,
    RMP_KEY_ALT_Z,

    // Special keys
    RMP_KEY_ENTER, RMP_KEY_SPACE, RMP_KEY_ESCAPE, RMP_KEY_UP, RMP_KEY_DOWN,
    RMP_KEY_LEFT, RMP_KEY_RIGHT, RMP_KEY_TAB, RMP_KEY_DELETE, RMP_KEY_HOME, RMP_KEY_END, RMP_KEY_BACKSPACE,

    // Function keys
    RMP_KEY_F1, RMP_KEY_F2, RMP_KEY_F3, RMP_KEY_F4, RMP_KEY_F5, RMP_KEY_F6,
    RMP_KEY_F7, RMP_KEY_F8, RMP_KEY_F9, RMP_KEY_F10, RMP_KEY_F11, RMP_KEY_F12,

    // Alphabet keys (lowercase)
    RMP_KEY_A, RMP_KEY_B, RMP_KEY_C, RMP_KEY_D, RMP_KEY_E, RMP_KEY_F, RMP_KEY_G, RMP_KEY_H,
    RMP_KEY_I, RMP_KEY_J, RMP_KEY_K, RMP_KEY_L, RMP_KEY_M, RMP_KEY_N, RMP_KEY_O, RMP_KEY_P,
    RMP_KEY_Q, RMP_KEY_R, RMP_KEY_S, RMP_KEY_T, RMP_KEY_U, RMP_KEY_V, RMP_KEY_W, RMP_KEY_X,
    RMP_KEY_Y, RMP_KEY_Z,

    // Alphabet keys (uppercase/shifted)
    RMP_KEY_SHIFT_A, RMP_KEY_SHIFT_B, RMP_KEY_SHIFT_C, RMP_KEY_SHIFT_D, RMP_KEY_SHIFT_E,
    RMP_KEY_SHIFT_F, RMP_KEY_SHIFT_G, RMP_KEY_SHIFT_H, RMP_KEY_SHIFT_I, RMP_KEY_SHIFT_J,
    RMP_KEY_SHIFT_K, RMP_KEY_SHIFT_L, RMP_KEY_SHIFT_M, RMP_KEY_SHIFT_N, RMP_KEY_SHIFT_O,
    RMP_KEY_SHIFT_P, RMP_KEY_SHIFT_Q, RMP_KEY_SHIFT_R, RMP_KEY_SHIFT_S, RMP_KEY_SHIFT_T,
    RMP_KEY_SHIFT_U, RMP_KEY_SHIFT_V, RMP_KEY_SHIFT_W, RMP_KEY_SHIFT_X, RMP_KEY_SHIFT_Y,
    RMP_KEY_SHIFT_Z,

    // Number keys
    RMP_KEY_0, RMP_KEY_1, RMP_KEY_2, RMP_KEY_3, RMP_KEY_4, RMP_KEY_5,
    RMP_KEY_6, RMP_KEY_7, RMP_KEY_8, RMP_KEY_9,

    // Symbol keys
    RMP_KEY_PLUS, RMP_KEY_MINUS, RMP_KEY_GT, RMP_KEY_LT, RMP_KEY_HASHTAG,
    RMP_KEY_DOLAR, RMP_KEY_PERSANT, RMP_KEY_STAR, RMP_KEY_DOT, RMP_KEY_UNDERS,
    RMP_KEY_SEMICOL, RMP_KEY_QUISTION_MARK, RMP_KEY_AT, RMP_KEY_OPCURB,
    RMP_KEY_CLCURB, RMP_KEY_BACK_SLASH, RMP_KEY_BACKTICK, RMP_KEY_OPEN_BRAKET,
    RMP_KEY_CLOSED_BRAKET, RMP_KEY_BAR, RMP_KEY_DBL_QUOTE, RMP_KEY_SINGLE_QOUTE, RMP_KEY_SLASH, RMP_KEY_COLON, RMP_KEY_COMMA,
    RMP_KEY_OPPAERN, RMP_KEY_CLPAREN, RMP_KEY_EQUAL,
    RMP_KEY_NONE
} rmp_key_t;

/**
 * Initialize keyboard input system
 * @return: true on success, false on failure
 */
bool rmp_keyboard_init(void);

/**
 * Get the currently pressed key
 * @return: key code, or RMP_KEY_NONE if no key is pressed
 */
rmp_key_t rmp_get_key(void);

/**
 * Close and clean up keyboard input system
 */
void rmp_keyboard_close(void);

#endif // RMP_KEYBOARD_H_